### PR TITLE
Adding Taint/UnTaint command support

### PR DESCRIPTION
**Pull request by rambabuiitk**
Adding Taint/UnTaint command support
Adding output name option support

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @rambabuiitk 
Thank you for the contribution.

Would you mind signing the CLA?

**Comment by rambabuiitk** [comment]
Hi Radek,

I have signed it.

**Comment by radeksimko** [comment]
@rambabuiitk It looks like you the email address which is used as the author in your commit here doesn't match the one that you have registered in GitHub and under which you signed the CLA, as the bot response mentioned.

Would you try to review your email address(es) and [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user), please?

**Comment by rambabuiitk** [comment]
closing this pull request. will raise another one

**Pull request closed without merging**
