### PR TITLE
fix force-copy

### LINKED ISSUE #262: Init() always gives `-force-copy` as an argument
Init() always gives `-force-copy` flag into the `terraform init` command.

https://github.com/hashicorp/terraform-exec/blob/v0.15.0/tfexec/init.go#L119

In my understanding, this means that the terraform always (re)initialization the backend  with `-migrate-state` even if `-reconfigure` is given.

https://www.terraform.io/cli/commands/init#backend-initialization

I consider that Init() should  remove `-force-copy` if it gives `-reconfigure` flag to the terraform command.

### PR DESCRIPTION
**Pull request by chanwit**
This PR fixes unconfigurable force-copy, and change its default value to be false.

Fixes #262

### CODE REVIEW

**Comment by Nalum** [comment]
Any chance of getting this in?

**Review by kmoe — APPROVED** [review]
Thanks for this PR - this was indeed an oversight and I agree with the fix.

The test failures should be fixed if you rebase your branch on `main`. I'll merge once tests pass.

**Comment by chanwit** [comment]
Thank you @kmoe 
I'm working on it.

**Comment by chanwit** [comment]
Hi again @kmoe 
It seems all tests passed, except the mac OS as it could not spin up the test environment.

**Comment by kmoe** [comment]
The `macosbuildtest` failure is unrelated to this PR and fixed in `main`, so I am merging this.

**Pull request merged**
