### PR TITLE
Add mac builds, speed up win builds

### PR DESCRIPTION
**Pull request by paultyng**

### CODE REVIEW

**Comment by paultyng** [comment]
@kmoe the plan things break on darwin too 😭

**Comment by radeksimko** [comment]
> the plan things break on darwin too

I fixed that in https://github.com/hashicorp/terraform-exec/pull/89 by skipping these tests on darwin, but we can add some more OS-dependent tests for both Windows and macOS.

**Comment by paultyng** [comment]
Rebased off your PR, #73 is the issue to fix the plan testing for other OS's.

**Comment by paultyng** [comment]
Unsure why these are still failing, I think something weird about the darwin runner but no idea what would cause it and don't have a Mac to investigate atm.

**Comment by radeksimko** [comment]
It just needed XCode/macOS version bump, because older Terraform versions, like 0.12.29 apparently can't be successfully compiled on older XCode/macOS under some circumstances - due to https://github.com/hashicorp/terraform/pull/24562

This is stderr captured from `terraform version` after it's compiled as part of the test:

```
runtime: netpoll: break fd ready for -2
        fatal error: runtime: netpoll: break fd ready for something unexpected

        runtime stack:
        runtime.throw(0x2aa7f25, 0x39)
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:1116 +0x72
        runtime.netpoll(0x2540a5275, 0x1)
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/netpoll_kqueue.go:147 +0x33e
        runtime.findrunnable(0xc00005c000, 0x0)
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:2434 +0x785
        runtime.schedule()
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:2669 +0x2d7
        runtime.park_m(0xc000102600)
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:2837 +0x9d
        runtime.mcall(0x80000)
        	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/asm_amd64.s:318 +0x5b

        goroutine 1 [runnable, locked to thread]:
        github.com/ChrisTrenkamp/goxpath/parser.init()
        	/private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/tfinstall-test979244961/vendor/github.com/ChrisTrenkamp/goxpath/parser/ast.go:19 +0xd05

        goroutine 35 [select]:
        go.opencensus.io/stats/view.(*worker).start(0xc00010ef00)
        	/private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/tfinstall-test979244961/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
        created by go.opencensus.io/stats/view.init.0
        	/private/var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/tfinstall-test979244961/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
```

**Review by radeksimko — APPROVED** [review]

**Pull request merged**
