### PR TITLE
Adds support for the terraform 0.12upgrade command

### PR DESCRIPTION
**Pull request by gdavison**
Adds support for the `terraform 0.12upgrade` command

### CODE REVIEW

**Comment by radeksimko** [comment]
👋   Hey Graham,
What is the intended use case for this command?

In general `terraform-exec` is used for automation (i.e. usually unattended execution) and from what I can tell the upgrade commands are _not_ intended to be used in a "fire & forget" way, because there are no guarantees that the upgraded config will be actually usable and it may require further manual changes.

**Comment by gdavison** [comment]
I'm using it for an enhancement to https://github.com/katbyte/terrafmt. It would allow users to apply `terraform 0.12` to any terraform blocks in Markdown or Go files.

**Review by kmoe — CHANGES_REQUESTED** [review]
Thanks for this. The use case is valid and the implementation sound. Thanks for including a unit test.

Happy to merge when an end-to-end test is added. There's a section in [CONTRIBUTING.md](https://github.com/hashicorp/terraform-exec/blob/master/CONTRIBUTING.md#end-to-end-tests) describing how to do this. If you don't have time, please let me know and I'll be happy to add it.

**Review by kmoe — APPROVED** [review]
LGTM

**Pull request merged**
